stages:
  - tests
# - secret-detection
  - quality-gate
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: maven
  paths:
    - .m2/repository

tests:
  stage: tests
  image: maven:3.9.9-eclipse-temurin-21
  tags:
    - common
  script:
    - mvn clean verify
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/Total/Total Coverage:/'
  coverage: '/\d+\%/'
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - target/*.jar
      - target/site/jacoco/
    reports:
      junit:
        - target/surefire-reports/*.xml
      coverage_report:
        coverage_format: cobertura
        path: target/site/jacoco/jacoco.xml
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'

quality-gate:
  stage: quality-gate
  image: maven:3.9.9-eclipse-temurin-21
  tags:
    - common
  needs:
    - job: tests
      artifacts: true
  script:
    - mvn sonar:sonar -Dsonar.qualitygate.wait=true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'

deploy:
  stage: deploy
  image: maven:3.9.9-eclipse-temurin-21
  tags:
    - common
  needs:
    - job: tests
      artifacts: true
  script:
    - mvn deploy -DskipTests
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'